name: "Publish Checkmarx SARIF to Pixee"
on:
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

jobs:
  share:
    name: Upload Checkmarx Results to Pixeebot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixee/upload-tool-results-action@v1
        with:
          tool: semgrep # Should be checkmarx but the effect of passing --sarif will be the same
          file: cx.sarif
          pixee-api-url: https://bdoyal.getpixee.com

